// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3yOckYrVZdnIPEteapZ_O6-H5EDnyCVo',
    appId: '1:486238943036:web:ed12159baf3e3c9cab1039',
    messagingSenderId: '486238943036',
    projectId: 'restaurant-waiter-order-system',
    authDomain: 'restaurant-waiter-order-system.firebaseapp.com',
    storageBucket: 'restaurant-waiter-order-system.firebasestorage.app',
    measurementId: 'G-N0K6TWR188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmbejZO5cIk4xDoMg_el0LGZNM1w4JA0',
    appId: '1:486238943036:android:6a7ff8c6f546d9feab1039',
    messagingSenderId: '486238943036',
    projectId: 'restaurant-waiter-order-system',
    storageBucket: 'restaurant-waiter-order-system.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaGNYWVU8H079bw3z3B5H0wa07-3dd5Q',
    appId: '1:486238943036:ios:14cf858b974a7a1dab1039',
    messagingSenderId: '486238943036',
    projectId: 'restaurant-waiter-order-system',
    storageBucket: 'restaurant-waiter-order-system.firebasestorage.app',
    iosBundleId: 'com.example.restoOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlaGNYWVU8H079bw3z3B5H0wa07-3dd5Q',
    appId: '1:486238943036:ios:14cf858b974a7a1dab1039',
    messagingSenderId: '486238943036',
    projectId: 'restaurant-waiter-order-system',
    storageBucket: 'restaurant-waiter-order-system.firebasestorage.app',
    iosBundleId: 'com.example.restoOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3yOckYrVZdnIPEteapZ_O6-H5EDnyCVo',
    appId: '1:486238943036:web:4200a529e4bc9e0aab1039',
    messagingSenderId: '486238943036',
    projectId: 'restaurant-waiter-order-system',
    authDomain: 'restaurant-waiter-order-system.firebaseapp.com',
    storageBucket: 'restaurant-waiter-order-system.firebasestorage.app',
    measurementId: 'G-R29CQSMGLR',
  );
}
